--- 
abstract: FITS utility routines
author: 
  - The Smithsonian Astrophysical Observatory
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: gpl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Astro-FITS-CFITSIO-Utils
no_index: 
  directory: 
    - inc
    - t
requires: 
  Astro::FITS::CFITSIO: 0
  Astro::FITS::CFITSIO::CheckStatus: 0
  Astro::FITS::Header::CFITSIO: 0
  Params::Validate: 0
  perl: 5.6.0
version: 0.11
